import "../styles/events.css";
import { useEffect, useState } from "react";
import Topbar from "../components/Topbar";
import { eventsApi } from "../services/api";
import { fmtDate, number } from "../utils/format";
import { FaCalendarAlt, FaSearch, FaPlus, FaEye, FaEdit, FaTrash } from "react-icons/fa";

const empty = { person_id: "", event_type: "", description: "", event_date: "", source: "" };
export default function Events() {
  const [events, setEvents] = useState([]), [total, setTotal] = useState(0), [q, setQ] = useState(""), [type, setType] = useState(""), [modal, setModal] = useState(null), [form, setForm] = useState(empty);
  const load = async () => { try { const r = await eventsApi.list({ q, type }); setEvents(r.data || []); setTotal(r.total || 0); } catch { setEvents([]); setTotal(0); } };
  useEffect(() => { load(); }, []); useEffect(() => { const t = setTimeout(load, 350); return () => clearTimeout(t); }, [q, type]);
  const save = async () => { if (modal === "create") await eventsApi.create(form); else await eventsApi.update(modal, form); setModal(null); load(); };
  const remove = async (e) => { if (confirm("Supprimer cet évènement ?")) { await eventsApi.remove(e.id); load(); } };
  return <><Topbar title="Gestion des évènements" /><div className="events-stats"><div className="stats-card"><div className="stats-icon"><FaCalendarAlt /></div><div><h3>Total évènements</h3><p>{number(total)}</p></div></div></div><div className="table-box"><div className="table-header"><div><h3>Liste des évènements</h3><span>Historique des faits liés aux personnes</span></div><button className="add-btn" onClick={() => { setForm(empty); setModal("create"); }}><FaPlus /> Ajouter</button></div><div className="filters-bar"><div className="search-box"><FaSearch className="search-icon" /><input value={q} onChange={(e) => setQ(e.target.value)} placeholder="Rechercher un évènement..." /></div><select value={type} onChange={(e) => setType(e.target.value)}><option value="">Tous les types</option><option>Naissance</option><option>Mariage</option><option>Divorce</option><option>Décès</option></select></div><table><thead><tr><th>ID</th><th>Type</th><th>Personne</th><th>Date</th><th>Source</th><th>Actions</th></tr></thead><tbody>{events.length === 0 && <tr><td colSpan="6" style={{ textAlign: "center", padding: 28 }}>Aucun évènement trouvé</td></tr>}{events.map((e) => <tr key={e.id}><td>{e.id}</td><td>{e.event_type || e.type || "—"}</td><td>{e.person_name || e.person || e.person_id || "—"}</td><td>{fmtDate(e.event_date || e.date)}</td><td>{e.source || "—"}</td><td><div className="action-buttons"><button className="view-btn"><FaEye /></button><button className="edit-btn" onClick={() => { setForm({ ...empty, ...e }); setModal(e.id); }}><FaEdit /></button><button className="delete-btn" onClick={() => remove(e)}><FaTrash /></button></div></td></tr>)}</tbody></table></div>{modal && <div className="modal-overlay"><div className="modal-box"><h3>{modal === "create" ? "Ajouter un évènement" : "Modifier évènement"}</h3><input placeholder="ID personne" value={form.person_id || ""} onChange={(e) => setForm({ ...form, person_id: e.target.value })} /><input placeholder="Type" value={form.event_type || form.type || ""} onChange={(e) => setForm({ ...form, event_type: e.target.value })} /><input type="datetime-local" value={form.event_date || ""} onChange={(e) => setForm({ ...form, event_date: e.target.value })} /><input placeholder="Source" value={form.source || ""} onChange={(e) => setForm({ ...form, source: e.target.value })} /><textarea placeholder="Description" value={form.description || ""} onChange={(e) => setForm({ ...form, description: e.target.value })} /><div className="modal-actions"><button className="cancel-btn" onClick={() => setModal(null)}>Annuler</button><button className="save-btn" onClick={save}>Enregistrer</button></div></div></div>}</>;
}
